### ISSUE TITLE
Suggest to loosen the dependency on dataset

### ISSUE THREAD

**Issue by Agnes-U** [burritosoftware/Nerdtendo#2]
Hi, your project Nerdtendo(commit id: 29527088ecec74cb661ab98b1a60adddc3dd13bd) requires "dataset==1.5.2" in its dependency. After analyzing the source code, we found that the following versions of dataset can also be suitable, i.e., dataset 1.5.1, since all functions that you directly (1 APIs: dataset.__init__.connect) or indirectly (propagate to 2 dataset's internal APIs and 7 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on dataset from "dataset==1.5.2" to "dataset>=1.5.1,<=1.5.2". This will improve the applicability of Nerdtendo and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on dataset?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by burritosoftware** [comment]
Who are ya? You have a ton of open issues, and this project is quite stale and inactive.
